### ISSUE TITLE
Nil filter not allowed.

### ISSUE THREAD

**Issue by kunalkushwaha** [kubernetes-incubator/cri-o#1079]
This is not bug as such, but I think `nil` shall be allowed to be passed to values like Filters for List API's.

e.g. 
``` go
 ListContainers(context.Background(), &pb.ListContainersRequest{}
```

Log
``` go
DEBU[2017-10-27 10:23:21.663524574+09:00] ListContainersRequest &ListContainersRequest{Filter:nil,} 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1d55a25]

goroutine 56 [running]:
github.com/kubernetes-incubator/cri-o/server.(*Server).ListContainers(0xc4205eae00, 0x7f47e5a1ea08, 0xc42027eff0, 0xc42053c000, 0xc4205eae00, 0x4308be, 0xc420187df0)
        /home/kunal/go/src/github.com/kubernetes-incubator/cri-o/server/container_list.go:40 +0x115
github.com/kubernetes-incubator/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime._RuntimeService_ListContainers_Handler(0x2223540, 0xc4205eae00, 0x7f47e5a1ea08, 0xc42027ef
f0, 0xc4202e6280, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/kunal/go/src/github.com/kubernetes-incubator/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/api.pb.go:3807 +0x28d
github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420093080, 0x33f7260, 0xc42044a000, 0xc4202f60f0, 0xc420217a40, 0x33c1f10, 0xc42027ef30, 0x0, 
0x0)
        /home/kunal/go/src/github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc/server.go:638 +0xb5c
github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420093080, 0x33f7260, 0xc42044a000, 0xc4202f60f0, 0xc42027ef30)

```

**Comment by runcom** [comment]
Looking
