### ISSUE TITLE
CreateContainerRequest: runtime error: index out of range

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes-incubator/cri-o#1312]
**Description**
CRIO master version crashes at container start with Kubernetes.
The image is successfully pulled though.

```
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: time="2018-02-06 19:39:39.085478463Z" level=debug msg="CreateContainerRequest &CreateContainerRequest{PodSandboxId:72b21692c70282122bf407eedf7c39924ba9e7e23149f34fe0a336d00dca64b1,Config:&ContainerConfig{Metadata:&ContainerMetadata{Name:nvidia-device-plugin-ctr,Attempt:0,},Image:&ImageSpec{Image:device-plugin@sha256:6a9b0c363c6a8904d120e43abac77ace2ce9977e2ef5a455678692ad5092b1c7,},Command:[],Args:[],WorkingDir:,Envs:[&KeyValue{Key:KUBE_DNS_PORT_53_UDP_PROTO,Value:udp,} &KeyValue{Key:KUBERNETES_PORT_443_TCP,Value:tcp://10.96.0.1:443,} &KeyValue{Key:KUBE_DNS_PORT,Value:udp://10.96.0.10:53,} &KeyValue{Key:KUBE_DNS_PORT_53_UDP_ADDR,Value:10.96.0.10,} &KeyValue{Key:KUBE_DNS_PORT_53_TCP,Value:tcp://10.96.0.10:53,} &KeyValue{Key:KUBE_DNS_PORT_53_TCP_PORT,Value:53,} &KeyValue{Key:KUBERNETES_PORT,Value:tcp://10.96.0.1:443,} &KeyValue{Key:KUBE_DNS_SERVICE_HOST,Value:10.96.0.10,} &KeyValue{Key:KUBE_DNS_SERVICE_PORT_DNS,Value:53,} &KeyValue{Key:KUBE_DNS_PORT_53_UDP_PORT,Value:53,} &KeyValue{Key:KUBE_DNS_PORT_53_TCP_PROTO,Value:tcp,} &KeyValue{Key:KUBERNETES_SERVICE_PORT_HTTPS,Value:443,} &KeyValue{Key:KUBERNETES_PORT_443_TCP_PROTO,Value:tcp,} &KeyValue{Key:KUBERNETES_PORT_443_TCP_PORT,Value:443,} &KeyValue{Key:KUBERNETES_PORT_443_TCP_ADDR,Value:10.96.0.1,} &KeyValue{Key:KUBE_DNS_SERVICE_PORT_DNS_TCP,Value:53,} &KeyValue{Key:KUBE_DNS_PORT_53_UDP,Value:udp://10.96.0.10:53,} &KeyValue{Key:KUBERNETES_SERVICE_HOST,Value:10.96.0.1,} &KeyValue{Key:KUBERNETES_SERVICE_PORT,Value:443,} &KeyValue{Key:KUBE_DNS_SERVICE_PORT,Value:53,} &KeyValue{Key:KUBE_DNS_PORT_53_TCP_ADDR,Value:10.96.0.10,}],Mounts:[&Mount{ContainerPath:/var/lib/kubelet/device-plugins,HostPath:/var/lib/kubelet/device-plugins,Readonly:false,SelinuxRelabel:false,Propagation:PROPAGATION_PRIVATE,} &Mount{ContainerPath:/var/run/secrets/kubernetes.io/serviceaccount,HostPath:/var/lib/kubelet/pods/dac6a7f2-0b73-11e8-857c-1230856b2dd0/volumes/kubernetes.io~secret/default-token-grcc5,Readonly:true,SelinuxRelabel:false,Propagation:PR
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: OPAGATION_PRIVATE,} &Mount{ContainerPath:/etc/hosts,HostPath:/var/lib/kubelet/pods/dac6a7f2-0b73-11e8-857c-1230856b2dd0/etc-hosts,Readonly:false,SelinuxRelabel:false,Propagation:PROPAGATION_PRIVATE,} &Mount{ContainerPath:/dev/termination-log,HostPath:/var/lib/kubelet/pods/dac6a7f2-0b73-11e8-857c-1230856b2dd0/containers/nvidia-device-plugin-ctr/5bf47b74,Readonly:false,SelinuxRelabel:false,Propagation:PROPAGATION_PRIVATE,}],Devices:[],Labels:map[string]string{io.kubernetes.container.name: nvidia-device-plugin-ctr,io.kubernetes.pod.name: nvidia-device-plugin-daemonset-jl2j7,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: dac6a7f2-0b73-11e8-857c-1230856b2dd0,},Annotations:map[string]string{io.kubernetes.container.hash: b27195b0,io.kubernetes.container.restartCount: 0,io.kubernetes.container.terminationMessagePath: /dev/termination-log,io.kubernetes.container.terminationMessagePolicy: File,io.kubernetes.pod.terminationGracePeriod: 30,},LogPath:nvidia-device-plugin-ctr_0.log,Stdin:false,StdinOnce:false,Tty:false,Linux:&LinuxContainerConfig{Resources:&LinuxContainerResources{CpuPeriod:0,CpuQuota:0,CpuShares:2,MemoryLimitInBytes:0,OomScoreAdj:1000,CpusetCpus:,CpusetMems:,},SecurityContext:&LinuxContainerSecurityContext{Capabilities:&Capability{AddCapabilities:[],DropCapabilities:[ALL],},Privileged:false,NamespaceOptions:&NamespaceOption{HostNetwork:false,HostPid:false,HostIpc:false,},SelinuxOptions:nil,RunAsUser:&Int64Value{Value:0,},RunAsUsername:,ReadonlyRootfs:false,SupplementalGroups:[],ApparmorProfile:,SeccompProfilePath:,NoNewPrivs:true,},},},SandboxConfig:&PodSandboxConfig{Metadata:&PodSandboxMetadata{Name:nvidia-device-plugin-daemonset-jl2j7,Uid:dac6a7f2-0b73-11e8-857c-1230856b2dd0,Namespace:kube-system,Attempt:0,},Hostname:nvidia-device-plugin-daemonset-jl2j7,LogDirectory:/var/log/pods/dac6a7f2-0b73-11e8-857c-1230856b2dd0,DnsConfig:&DNSConfig{Servers:[10.96.0.10],Searches:[kube-system.svc.cluster.local svc.cluster.local cluster.local ec2.internal],Options:[ndots:5],},PortMappings:[],Labels:map[st
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: ring]string{controller-revision-hash: 1723966783,io.kubernetes.pod.name: nvidia-device-plugin-daemonset-jl2j7,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: dac6a7f2-0b73-11e8-857c-1230856b2dd0,name: nvidia-device-plugin-ds,pod-template-generation: 1,},Annotations:map[string]string{kubernetes.io/config.seen: 2018-02-06T19:38:06.778701086Z,kubernetes.io/config.source: api,},Linux:&LinuxPodSandboxConfig{CgroupParent:/kubepods/besteffort/poddac6a7f2-0b73-11e8-857c-1230856b2dd0,SecurityContext:&LinuxSandboxSecurityContext{NamespaceOptions:&NamespaceOption{HostNetwork:false,HostPid:false,HostIpc:false,},SelinuxOptions:nil,RunAsUser:nil,ReadonlyRootfs:false,SupplementalGroups:[],Privileged:false,SeccompProfilePath:,},Sysctls:map[string]string{},},},}"
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: time="2018-02-06 19:39:39.088386316Z" level=warning msg="requested logPath for ctr id ee5c29a7f4289eac672cdb993be0c8b3170e1570f3e0d4f097d1f60c28d7fd1a is a relative path: nvidia-device-plugin-ctr_0.log"
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: time="2018-02-06 19:39:39.088411360Z" level=debug msg="setting container's log_path" ctr.logfile="nvidia-device-plugin-ctr_0.log" log_path="nvidia-device-plugin-ctr_0.log" sbox.logdir=
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: panic: runtime error: index out of range
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: goroutine 102 [running]:
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: github.com/kubernetes-incubator/cri-o/vendor/github.com/opencontainers/runtime-tools/generate.glob..func1(0xc4200a4fc0, 0x5, 0xe, 0xc, 0x1, 0x9, 0xe)
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]:         /home/ubuntu/go/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/opencontainers/runtime-tools/generate/generate.go:23 +0xab
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: github.com/kubernetes-incubator/cri-o/vendor/github.com/opencontainers/runtime-tools/generate.(*Generator).DropProcessCapabilityPermitted(0xc4202186c0, 0xc420499cf0, 0x8, 0x0, 0x0)
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]:         /home/ubuntu/go/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/opencontainers/runtime-tools/generate/generate.go:1228 +0x172
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: github.com/kubernetes-incubator/cri-o/server.setupCapabilities(0xc4202186c0, 0xc42027f8c0, 0x2, 0xc42094cc80)
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]:         /home/ubuntu/go/src/github.com/kubernetes-incubator/cri-o/server/container_create.go:544 +0xc57
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: github.com/kubernetes-incubator/cri-o/server.(*Server).createSandboxContainer(0xc4204e4a80, 0x7f938434a778, 0xc42027f6b0, 0xc4209490c0, 0x40, 0xc420453d00, 0x74, 0xc420370c60, 0xc42091f080, 0xc420180dd0, ...)
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]:         /home/ubuntu/go/src/github.com/kubernetes-incubator/cri-o/server/container_create.go:934 +0x7b33
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: github.com/kubernetes-incubator/cri-o/server.(*Server).CreateContainer(0xc4204e4a80, 0x7f938434a778, 0xc42027f6b0, 0xc420376b80, 0x0, 0x0, 0x0)
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]:         /home/ubuntu/go/src/github.com/kubernetes-incubator/cri-o/server/container_create.go:692 +0x4b1
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: github.com/kubernetes-incubator/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime._RuntimeService_CreateContainer_Handler(0x183a520, 0xc4204e4a80, 0x7f938434a778, 0xc42027f6b0, 0xc420494fa0, 0x0, 0x0, 0x0, 0xc420977c14, 0xc420977c20)
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]:         /home/ubuntu/go/src/github.com/kubernetes-incubator/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/api.pb.go:3995 +0x276
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4202ce000, 0x25c2ea0, 0xc420554e10, 0xc42083c4b0, 0xc42049a150, 0x2591dd0, 0xc42027f680, 0x0, 0x0)
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]:         /home/ubuntu/go/src/github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc/server.go:638 +0x99c
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4202ce000, 0x25c2ea0, 0xc420554e10, 0xc42083c4b0, 0xc42027f680)
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]:         /home/ubuntu/go/src/github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc/server.go:796 +0x11d8
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420498100, 0xc4202ce000, 0x25c2ea0, 0xc420554e10, 0xc42083c4b0)
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]:         /home/ubuntu/go/src/github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc/server.go:449 +0x9f
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]: created by github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
Feb 06 19:39:39 ip-172-31-9-198 crio[18872]:         /home/ubuntu/go/src/github.com/kubernetes-incubator/cri-o/vendor/google.golang.org/grpc/server.go:447 +0xa1
Feb 06 19:39:39 ip-172-31-9-198 systemd[1]: crio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 06 19:39:39 ip-172-31-9-198 systemd[1]: crio.service: Unit entered failed state.
Feb 06 19:39:39 ip-172-31-9-198 systemd[1]: crio.service: Failed with result 'exit-code'.

```
**Steps to reproduce the issue:**
1. Build CRIO master
2. Setup Kubelet with the CRIO connection after following [these instructions](https://github.com/kubernetes-incubator/cri-o/blob/master/kubernetes.md)
3. Run a pod that lands on the CRIO node

**Describe the results you received:**
CRIO Crashes.

**Describe the results you expected:**
Container starts normally.
It works on release-1.9

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
crio version 1.9.0-dev
commit: "eaf5b08c8ff20259b0f3b1763115fecc704f9681"
```

**Output of `runc --version`:**
```
runc version 1.0.0-rc4+dev
commit: 9f9c96235cc97674e935002fc3d78361b696a69e
spec: 1.0.0
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- AWS
- p2.xlarge
- 
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```
- /etc/containers/policy.json is cri-o/test/policy.json
- /etc/crio/seccomp.json is cri-o/seccomp.json
- 
```
$ sudo ls /opt/cni/bin/
bridge  flannel     ipvlan    macvlan  ptp     tuning
dhcp    host-local  loopback  portmap  sample  vlan
$ sudo ls /etc/cni/net.d/
10-crio-bridge.conf  10-flannel.conf  99-loopback.conf  README.md
```

Thanks!

**Comment by mrunalp** [comment]
I suspect that https://github.com/kubernetes-incubator/cri-o/pull/1269/files might be the cause. Could you revert that commit (https://github.com/kubernetes-incubator/cri-o/pull/1269/commits/523326b7ba15e6e38fd4d1716d78c860ac1ad4fa) and see if it works for you?

**Comment by mrunalp** [comment]
@RenaudWasTaken What version of kube are you testing with? (Trying to reproduce it locally).

**Comment by runcom** [comment]
> I suspect that https://github.com/kubernetes-incubator/cri-o/pull/1269/files might be the cause. Could you revert that commit (523326b) and see if it works for you?

that commit has surely shown a bug in runtime-tools https://github.com/opencontainers/runtime-tools/pull/581

@RenaudWasTaken could you please provide a full reproducer with kube version and everything so we can test it out?

**Comment by RenaudWasTaken** [comment]
kubelet version was release-1.9
And the pod that ran was the flannel daemonset

Will try to give you more information when I have more time to spin up a CRI-O machine :)

**Comment by RenaudWasTaken** [comment]
I can confirm this bug doesn't happen with master :)
