### ISSUE TITLE
Bump containers/image (dep is broken right now)

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#551]
We need https://github.com/containers/image/pull/280 but `dep` is completely broken for me:

```
10:02:47 [github.com/kubernetes-incubator/cri-o] ‹master› dep ensure -v -update github.com/containers/image
panic: shouldn't be possible unable to deduce repository and source type for: "k8s.io/kube-apiextensions-server/pkg/apis/apiextensions"

goroutine 1 [running]:
panic(0x795e60, 0xc421224290)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*solver).selectRoot(0xc420444960, 0xc420bdf620, 0xc420bdf6b0)
        /home/amurdaca/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/solver.go:485 +0xac8
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*solver).Solve(0xc420444960, 0x3b, 0xc4200140da, 0x25, 0xc4201bac30)
        /home/amurdaca/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/solver.go:331 +0x6a
main.(*ensureCommand).Run(0xc420137960, 0xc42015d570, 0xc42000c130, 0x1, 0x1, 0x0, 0x0)
        /home/amurdaca/go/src/github.com/golang/dep/cmd/dep/ensure.go:145 +0x4a2
main.main()
        /home/amurdaca/go/src/github.com/golang/dep/cmd/dep/main.go:97 +0x652
```

`k8s.io/kube-apiextensions-server/pkg/apis/apiextensions` is a meta package which doesn't (yet) have a github repo, rather it stays here https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kube-apiextensions-server

**Comment by rhatdan** [comment]
@runcom Is this still an issue?

**Comment by runcom** [comment]
nope
